server:
  port: 9000
spring:
  application:
    name: @artifactId@
  servlet:
    multipart:
      max-file-size: 100MB      # Single file max size
      max-request-size: 100MB   # All files max size
